name: Windows Agents Release (Manual Test)

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build-windows-agents-test-release:
    name: Build and publish test Windows agents
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: true
      upload-tag: leehollow-test
      windows-only: true
      include-windows-sciter: false
    secrets: inherit
